name: release_docker

on:
  workflow_call:
    inputs:
      working-directory:
        default: "docker"
        type: string
        description: "From which folder this pipeline executes"
      dockerfile:
        required: true
        type: string
        description: "Name of the Dockerfile to build, relative to the working directory"
      image-name:
        required: true
        type: string
        description: "Name of the image to build"

env:
  TEST_TAG: ${{ inputs.image-name }}:test
  LATEST_TAG: ${{ inputs.image-name }}:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} python -c "import langchain"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm64
          # push: true
          tags: ${{ env.LATEST_TAG }}
